//! Standard-unicode emoji dataset access, isolated so the dataset is
//! referenced from exactly **one** place and only on the hydrate (wasm)
//! target. ssr gets inert stubs, so the server renders an unknown `:name:`
//! literally and hydrate swaps in the glyph — the same text-content pattern
//! the channel view already uses for local-time timestamps, so there's no
//! jarring hydration mismatch.
//!
//! The hydrate path lazy-fetches `/emoji.json` (pre-generated by
//! `examples/gen_emoji_json.rs` at repo-build time) on first call and caches
//! the parsed table for the page session in a `OnceLock`. A second
//! `OnceLock<ArcRwSignal<u32>>` is bumped once the load completes so leptos
//! views that subscribed (the emoji picker) re-render and pick up the data;
//! the message-render resolver path stays non-reactive and falls back to the
//! literal `:name:` on the brief pre-load window, mirroring an unknown
//! shortcode (the markup parser already handles that case gracefully).
//!
//! Coalescing: an `AtomicBool` guards in-flight fetches so multiple call
//! sites (composer mount + first picker open + first `:trigger` autocomplete
//! hit) collapse into a single network round-trip.
//!
//! Sizes (M7/D1, measured 2026-05-28): pulling the `emojis` crate's static
//! phf table into the wasm cost **~79 KB brotli**; the equivalent JSON asset
//! is ~22 KB brotli, fetched lazily and cached for the session. The win is
//! the bundle, not the wire — interactive-load happens off the hot path.

/// One standard-unicode emoji surfaced to the picker / autocomplete. `Copy`
/// and all-`&'static str` so it threads cheaply through view code; the
/// strings are leaked once on JSON parse, so total runtime allocation is
/// bounded by the (one-time) dataset.
#[derive(Clone, Copy)]
pub struct StdEmoji {
    /// The unicode glyph, e.g. `"😄"`.
    pub glyph: &'static str,
    /// The primary github-style shortcode, without colons, e.g. `"smile"`.
    pub shortcode: &'static str,
}

/// Emoji group display labels, in picker order. Kept as a `const` so the
/// shell can render group headers before the dataset has loaded (the items
/// under each header just appear when the JSON resolves).
pub const GROUPS: &[&str] = &[
    "Smileys & Emotion",
    "People & Body",
    "Animals & Nature",
    "Food & Drink",
    "Travel & Places",
    "Activities",
    "Objects",
    "Symbols",
    "Flags",
];

/// Kick off the lazy JSON fetch if it hasn't started yet. Cheap to call from
/// multiple sites (composer mount, app shell mount, first `:trigger` hit) —
/// in-flight fetches coalesce via [`real::PENDING`]. No-op on ssr.
pub fn warm() {
    #[cfg(feature = "hydrate")]
    real::warm();
}

#[cfg(feature = "hydrate")]
pub use real::{by_group, glyph, search};

#[cfg(not(feature = "hydrate"))]
pub use stub::{by_group, glyph, search};

#[cfg(feature = "hydrate")]
mod real {
    use super::StdEmoji;
    use leptos::prelude::*;
    use leptos::reactive::signal::ArcRwSignal;
    use std::collections::HashMap;
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::sync::OnceLock;

    /// Loaded + indexed dataset. Filled exactly once per page session.
    struct Dataset {
        /// All entries in source-file order, for `by_group` iteration.
        all: Vec<StdEmoji>,
        /// Per-group entry list, keyed by the [`super::GROUPS`] label.
        by_group: HashMap<&'static str, Vec<StdEmoji>>,
        /// Shortcode → glyph for the message-render fast path.
        glyph_by_shortcode: HashMap<&'static str, &'static str>,
        /// Lowercased (name, primary shortcode) for the picker's substring
        /// search. Parallel index into `all`. Names + shortcodes are leaked
        /// at parse time so the search loop stays alloc-free per call.
        search_index: Vec<(&'static str, &'static str)>,
    }

    static DATA: OnceLock<Dataset> = OnceLock::new();
    static PENDING: AtomicBool = AtomicBool::new(false);
    /// Revision counter bumped from 0 → 1 when the dataset finishes loading.
    /// Views that want to re-render on load completion `.get()` this signal;
    /// callers that don't (e.g. the message-render resolver) just observe
    /// `None` until then. `ArcRwSignal` lives outside any reactive owner, so
    /// the static `OnceLock` is the right home.
    static REV: OnceLock<ArcRwSignal<u32>> = OnceLock::new();

    fn rev() -> &'static ArcRwSignal<u32> {
        REV.get_or_init(|| ArcRwSignal::new(0))
    }

    /// The unicode glyph for a github `:shortcode:`, if it is a standard
    /// emoji. `None` for unknown or custom shortcodes (the caller falls back
    /// to either a custom guild emoji or the literal text), and `None` if
    /// the JSON dataset hasn't loaded yet — a transient window the message
    /// renderer treats as "unknown shortcode" (= renders literally), which
    /// the markup parser already handles.
    pub fn glyph(shortcode: &str) -> Option<&'static str> {
        match DATA.get() {
            Some(d) => d.glyph_by_shortcode.get(shortcode).copied(),
            None => {
                warm();
                None
            }
        }
    }

    /// Up to `limit` standard emoji whose CLDR name or primary shortcode
    /// contains the (lowercased) query. Linear scan over the parsed table —
    /// trivial at this size (~1.9k entries), cheaper than the grid's DOM
    /// render, so no index is built.
    pub fn search(query: &str, limit: usize) -> Vec<StdEmoji> {
        // Subscribe so the picker re-renders when the dataset arrives.
        rev().get();
        let Some(d) = DATA.get() else {
            warm();
            return Vec::new();
        };
        let q = query.trim().to_lowercase();
        if q.is_empty() {
            return Vec::new();
        }
        d.search_index
            .iter()
            .enumerate()
            .filter_map(|(i, (name, sc))| {
                (name.contains(q.as_str()) || sc.contains(q.as_str())).then_some(d.all[i])
            })
            .take(limit)
            .collect()
    }

    /// Every standard emoji in the group named by `label` (one of
    /// [`super::GROUPS`]), for the picker's category sections.
    pub fn by_group(label: &str) -> Vec<StdEmoji> {
        rev().get();
        let Some(d) = DATA.get() else {
            warm();
            return Vec::new();
        };
        d.by_group.get(label).cloned().unwrap_or_default()
    }

    /// Spawn the JSON fetch if no other call site has already started one.
    /// Idempotent and re-entrant — multiple calls before the first one
    /// finishes are folded into a single network round-trip.
    pub fn warm() {
        if DATA.get().is_some() {
            return;
        }
        if PENDING
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .is_err()
        {
            return;
        }
        leptos::task::spawn_local(async move {
            match fetch_and_parse().await {
                Ok(d) => {
                    let _ = DATA.set(d);
                    // Wake up any reactive consumer (the picker re-renders).
                    rev().set(1);
                }
                Err(_) => {
                    // Reset the gate so a later call can retry. Network may
                    // come back; the picker stays empty in the meantime.
                    PENDING.store(false, Ordering::Release);
                }
            }
        });
    }

    async fn fetch_and_parse() -> Result<Dataset, ()> {
        let resp = gloo_net::http::Request::get("/emoji.json")
            .send()
            .await
            .map_err(|_| ())?;
        if !resp.ok() {
            return Err(());
        }
        let raw: RawDataset = resp.json().await.map_err(|_| ())?;
        Ok(index(raw))
    }

    #[derive(serde::Deserialize)]
    struct RawDataset {
        #[allow(dead_code)]
        groups: Vec<String>,
        items: Vec<RawEntry>,
    }

    #[derive(serde::Deserialize)]
    struct RawEntry {
        glyph: String,
        shortcode: String,
        group: String,
        name: String,
    }

    /// Materialise the parsed JSON into a `Dataset` with leaked `&'static`
    /// strings. Leak is intentional and bounded — the dataset is allocated
    /// exactly once per page session, and `&'static str` keeps `StdEmoji`
    /// trivially `Copy` for the view code.
    fn index(raw: RawDataset) -> Dataset {
        let mut all = Vec::with_capacity(raw.items.len());
        let mut by_group: HashMap<&'static str, Vec<StdEmoji>> = HashMap::new();
        let mut glyph_by_shortcode: HashMap<&'static str, &'static str> = HashMap::new();
        let mut search_index = Vec::with_capacity(raw.items.len());
        for entry in raw.items {
            // Match each raw group string against the const GROUPS so the
            // hashmap key is a stable `&'static str` (cheaper hashing, and
            // the picker's `data::by_group(label)` looks up by the same
            // `&'static str` it iterates from `GROUPS`).
            let group_static = super::GROUPS
                .iter()
                .copied()
                .find(|g| **g == entry.group)
                .unwrap_or("");
            let glyph: &'static str = Box::leak(entry.glyph.into_boxed_str());
            let shortcode: &'static str = Box::leak(entry.shortcode.into_boxed_str());
            let name_lower: &'static str = Box::leak(entry.name.to_lowercase().into_boxed_str());
            let std = StdEmoji { glyph, shortcode };
            all.push(std);
            by_group.entry(group_static).or_default().push(std);
            glyph_by_shortcode.insert(shortcode, glyph);
            search_index.push((name_lower, shortcode));
        }
        Dataset {
            all,
            by_group,
            glyph_by_shortcode,
            search_index,
        }
    }
}

// ssr never compiles the hydrate-only fetch path, so these inert stubs keep
// the shared call sites type-checking on the server. The server renders an
// unknown `:name:` literally; hydrate swaps in the glyph once the JSON
// loads.
#[cfg(not(feature = "hydrate"))]
mod stub {
    use super::StdEmoji;

    pub fn glyph(_shortcode: &str) -> Option<&'static str> {
        None
    }
    pub fn search(_query: &str, _limit: usize) -> Vec<StdEmoji> {
        Vec::new()
    }
    pub fn by_group(_label: &str) -> Vec<StdEmoji> {
        Vec::new()
    }
}
